// src/api/chat-session/routes/chat-session.js
module.exports = {
  routes: [
    // Existing default routes generated by Strapi CLI (if any)
    // {
    //   method: 'GET',
    //   path: '/chat-sessions',
    //   handler: 'api::chat-session.chat-session.find',
    //   config: { policies: [] }
    // },
    // {
    //   method: 'GET',
    //   path: '/chat-sessions/:id',
    //   handler: 'api::chat-session.chat-session.findOne',
    //   config: { policies: [] }
    // },

    // Custom route for listing user's chat sessions
    {
      method: 'GET',
      path: '/chat/sessions', // Your desired custom endpoint
      handler: 'api::chat-session.chat-session.find', // Points to the custom find method
      config: {
        policies: [], // Add authentication/authorization policies here
        middlewares: [],
      },
    },
  ],
};