// src/api/chat-message/routes/chat-message.js
module.exports = {
  routes: [
    // Existing default routes generated by Strapi CLI (if any)
    // {
    //   method: 'GET',
    //   path: '/chat-messages',
    //   handler: 'api::chat-message.chat-message.find',
    //   config: { policies: [] }
    // },
    // {
    //   method: 'GET',
    //   path: '/chat-messages/:id',
    //   handler: 'api::chat-message.chat-message.findOne',
    //   config: { policies: [] }
    // },

    // Custom route for sending messages
    {
      method: 'POST',
      path: '/chat/send', // Your desired custom endpoint
      handler: 'api::chat-message.chat-message.create', // Points to the custom create method
      config: {
        policies: [], // Add authentication/authorization policies here if needed
        middlewares: [],
      },
    },
    // Custom route for fetching messages by session ID (cleaner than filters)
    // You might prefer this over the default `find` with filters.
    // Make sure to adapt the `find` method in the controller to expect `ctx.params.sessionId`
    // {
    //   method: 'GET',
    //   path: '/chat/messages/:sessionId', // e.g., /api/chat/messages/chat-1-2
    //   handler: 'api::chat-message.chat-message.findMessagesBySession', // You'd need a new method name
    //   config: { policies: [] }
    // },
  ],
};